# Generated by Django 5.2.6 on 2025-09-12 15:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of brand')),
                ('country', models.CharField(max_length=50, verbose_name='brand country')),
                ('style', models.CharField(blank=True, max_length=100, verbose_name='style')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clothing_brands/logos/')),
            ],
            options={
                'verbose_name': 'name of brand',
                'verbose_name_plural': 'name of brands',
            },
        ),
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('category_type', models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids'), ('unisex', 'unisex')], max_length=20, verbose_name='category type')),
                ('garment_type', models.CharField(choices=[('shirt', 'shirt'), ('pants', 'pants'), ('jacket', 'jacket'), ('dress', 'dress'), ('underwear', 'underwear'), ('shoes', 'shoes'), ('accessory', 'accessory')], max_length=20, verbose_name='garment type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='color name')),
                ('hex_code', models.CharField(blank=True, max_length=7, verbose_name='HEX Code')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='size')),
                ('size_type', models.CharField(choices=[('clothing', 'clothing'), ('shoes', 'shoes'), ('accessory', 'accessory')], max_length=20, verbose_name='size type')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='description')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizs',
            },
        ),
        migrations.CreateModel(
            name='ClothingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='product name')),
                ('collection_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)], verbose_name='سال مجموعه')),
                ('description', models.TextField(verbose_name='description')),
                ('material', models.CharField(choices=[('cotton', 'cotton'), ('polyester', 'polyester'), ('wool', 'wool'), ('silk', 'silk'), ('denim', 'denim'), ('leather', 'leather'), ('mixed', 'mixed')], max_length=20, verbose_name='material')),
                ('material_composition', models.CharField(blank=True, max_length=200, verbose_name='material composition')),
                ('care_instructions', models.TextField(blank=True, verbose_name='care instructions')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price with discount')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='product code')),
                ('condition', models.CharField(choices=[('new', 'new'), ('used', 'used')], max_length=20, verbose_name='condition')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_fashionstore.clothingbrand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_fashionstore.clothingcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'name of product',
                'verbose_name_plural': 'name of products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price modifier')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_fashionstore.color', verbose_name='color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='c_fashionstore.clothingproduct')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_fashionstore.size', verbose_name='size')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'products variant',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ClothingProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothing/products/images/')),
                ('alt_text', models.CharField(blank=True, max_length=100, verbose_name='alt text')),
                ('is_main', models.BooleanField(default=False, verbose_name='main image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='c_fashionstore.clothingproduct')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='c_fashionstore.color', verbose_name='colors')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='c_fashionstore.productvariant')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'iamges',
            },
        ),
    ]
