# Generated by Django 5.2.6 on 2025-09-13 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_fashionstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingproduct',
            name='collection_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)], verbose_name='collection year'),
        ),
    ]
