# Generated by Django 5.2.6 on 2025-09-20 09:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='brand name')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('established_year', models.IntegerField(verbose_name='established year')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
            ],
            options={
                'verbose_name': 'brand name',
                'verbose_name_plural': 'brands name',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('category_type', models.CharField(choices=[('mobile', 'mobile'), ('laptop', 'laptop'), ('desktop', 'desktop'), ('console', 'console'), ('accessory', 'accessory'), ('audio', 'audio')], max_length=20, verbose_name='category type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='product name')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='model')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='release year')),
                ('description', models.TextField(verbose_name='description')),
                ('specifications', models.JSONField(default=dict, verbose_name='technical specifications')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='discount price')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='product sku')),
                ('condition', models.CharField(choices=[('new', 'new'), ('used', 'used'), ('refurbished', 'refurbished')], max_length=20, verbose_name='condition')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_techstore.brand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_techstore.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='screen size (inch)')),
                ('resolution', models.CharField(max_length=50, verbose_name='resolution')),
                ('ram', models.IntegerField(verbose_name='RAM (GB)')),
                ('storage', models.IntegerField(verbose_name='storage (GB)')),
                ('battery', models.IntegerField(verbose_name='battery (mAh)')),
                ('camera_main', models.CharField(max_length=100, verbose_name='main camera')),
                ('camera_front', models.CharField(max_length=100, verbose_name='front camera')),
                ('os', models.CharField(max_length=50, verbose_name='OS')),
                ('cpu', models.CharField(max_length=100, verbose_name='CPU')),
                ('gpu', models.CharField(blank=True, max_length=100, verbose_name='GPU')),
                ('sim_count', models.IntegerField(default=1, verbose_name='sim count')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='weight (g)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_specs', to='b_techstore.product')),
            ],
            options={
                'verbose_name': 'mobile specification',
                'verbose_name_plural': 'mobiles specification',
            },
        ),
        migrations.CreateModel(
            name='LaptopSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='screen size (inch)')),
                ('resolution', models.CharField(max_length=50, verbose_name='resolution')),
                ('ram', models.IntegerField(verbose_name='RAM (GB)')),
                ('storage', models.IntegerField(verbose_name='storage (GB)')),
                ('storage_type', models.CharField(choices=[('hdd', 'HDD'), ('ssd', 'SSD'), ('nvme', 'NVMe')], max_length=20, verbose_name='storage type')),
                ('cpu', models.CharField(max_length=100, verbose_name='cpu')),
                ('gpu', models.CharField(max_length=100, verbose_name='gpu')),
                ('os', models.CharField(max_length=50, verbose_name='OS')),
                ('battery_life', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='battery life')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='weight (kg)')),
                ('ports', models.TextField(blank=True, verbose_name='ports')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_specs', to='b_techstore.product')),
            ],
            options={
                'verbose_name': 'laptop specification',
                'verbose_name_plural': 'laptops specification',
            },
        ),
        migrations.CreateModel(
            name='ConsoleSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField(verbose_name='storage (GB)')),
                ('cpu', models.CharField(max_length=100, verbose_name='cpu')),
                ('gpu', models.CharField(max_length=100, verbose_name='gpu')),
                ('ram', models.IntegerField(verbose_name='RAM (GB)')),
                ('max_resolution', models.CharField(max_length=50, verbose_name='max resolution')),
                ('controller_included', models.BooleanField(default=True, verbose_name='controller included')),
                ('vr_support', models.BooleanField(default=False, verbose_name='vr support')),
                ('online_features', models.TextField(blank=True, verbose_name='online_features')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='console_specs', to='b_techstore.product')),
            ],
            options={
                'verbose_name': 'console specification',
                'verbose_name_plural': 'consoles specification',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('alt_text', models.CharField(blank=True, max_length=100, verbose_name='alt text')),
                ('is_main', models.BooleanField(default=False, verbose_name='main')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='b_techstore.product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
            },
        ),
    ]
