# Generated by Django 5.2.6 on 2025-09-13 16:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_bookstore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_material', models.CharField(blank=True, max_length=100)),
                ('cover_finish', models.CharField(blank=True, max_length=100)),
                ('binding_type', models.CharField(blank=True, max_length=100)),
                ('binding_durability', models.CharField(blank=True, max_length=100)),
                ('ink_type', models.CharField(blank=True, help_text='ink type', max_length=100)),
                ('environmental_friendly', models.BooleanField(default=False, verbose_name='environmental friendly')),
                ('made_in', models.CharField(blank=True, max_length=100, verbose_name='made in ...')),
                ('warranty_period', models.CharField(blank=True, help_text='example: 6 months', max_length=50)),
                ('return_policy', models.TextField(blank=True, help_text='return policy')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='a_bookstore.book')),
                ('paper_quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_bookstore.paperquality')),
                ('printing_quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_bookstore.printingquality')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('verified_purchase', models.BooleanField(default=False, verbose_name='verified purchase')),
                ('helpful_yes', models.PositiveIntegerField(default=0)),
                ('helpful_no', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='a_bookstore.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'unique_together': {('book', 'user')},
            },
        ),
    ]
